todo_backend/todo/urls.py
from django.conf.urls import url
from . import views
from .views import *
from .api.routers import router


urlpatterns = [
    url(r'^registration/$', UserRegistrationView.as_view(), name='registration'),
    url(r'^login/$', UserLoginView.as_view(), name='login'),
    url(r'^logout/$', UserLogoutView.as_view(), name='logout'),
    url(r'^$', MainPageView.as_view(), name='main'),
    url(r'^create/$', CreateToDoView.as_view(), name='create'),
    url(r'^list/$', ToDoListView.as_view(), name='list'),
    url(r'^update/(?P<pk>\d+)/$', UpdateToDoView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', DeleteToDoView.as_view(), name='delete'),
    url(r'^deleted/$', DeletedView.as_view(), name='deleted'),
    url(r'^share/(?P<pk>\d+)/$', ShareTaskView.as_view(), name='share'),
    url(r'^task/(?P<pk>\d+)/$', TaskDetailView.as_view(), name='task'),
    url(r'^shared_tasks/$', SharedTasksListView.as_view(), name='shared_tasks'),
]

urlpatterns += router.urls

todo_backend/todo_backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^', include('todo.urls', namespace='to_do')),
]

todo_backend/todo/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import ReadOnlyPasswordHashField, AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from .models import ToDoTask, ShareTask
User = get_user_model()


class BaseUserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given email and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(label=_("Пороль"),
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label=_("Повторите пороль"),
                                widget=forms.PasswordInput(attrs={'placeholder': 'Re-enter Password'}),
                                help_text=_("Enter the same password as above, for verification."))

    class Meta:
        model = User
        fields = ("email", "first_name", "last_name")

    def __init__(self, *args, **kwargs):
        super(BaseUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.TextInput(attrs={
            'placeholder': 'Email'})
        self.fields['first_name'].widget = forms.TextInput(attrs={
            'placeholder': 'First name'})
        self.fields['last_name'].widget = forms.TextInput(attrs={
            'placeholder': 'Last name'})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(BaseUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class BaseUserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(label=_("Password"),
                                         help_text=_("Raw passwords are not stored, so there is no way to see "
                                                     "this user's password, but you can change the password "
                                                     "using <a href=\"../password/\">this form</a>."))

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(BaseUserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial["password"]


class UserRegistrationForm(BaseUserCreationForm):
    accept = forms.BooleanField(initial=False,
                                label=_('I accept the terms of the user agreement.'),
                                error_messages={'required': _("You must confirm this rule.")})


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=254, label=_("Логин"))
    password = forms.CharField(label=_("Пароль"), widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(UserAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'placeholder': 'E-mail:'})
        self.fields['password'].widget = forms.PasswordInput(attrs={
            'placeholder': 'Password:'})


class CreateTaskForm(forms.ModelForm):
    error_messages = {
        'date_error': _("End date must be more than start date"),
    }

    class Meta:
        model = ToDoTask
        fields = ('title', 'description', 'start_date', 'end_date')

    def clean_end_date(self):
        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')
        if start_date is not None and end_date is not None:
            if start_date >= end_date:
                raise forms.ValidationError(
                    self.error_messages['date_error'],
                    code='date_error',
                )
        return end_date


class UpdateTaskForm(CreateTaskForm):

    start_date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])
    end_date = forms.DateTimeField(input_formats=['%Y-%m-%d %H:%M:%S'])

    class Meta:
        model = ToDoTask
        fields = ('title', 'description', 'start_date', 'end_date')


class SearchForm(forms.Form):
   user_name = forms.CharField(required=True)


class CommentForm(forms.Form):
   comment = forms.CharField(widget=forms.Textarea, required=True)


class ShareTaskForm(forms.ModelForm):

    def clean(self):
        share_users = self.cleaned_data.get('share_users')
        task = self.cleaned_data.get('task')
        if task:
            all_user_list = []
            creator = task.task_creator
            for user in share_users:
                all_user_list.append(user)
            if creator in all_user_list:
                raise forms.ValidationError(
                    'Task creator cannot be included in the task share user list'
                )
        # share_tasks = ShareTask.objects.filter(task=task)
        # task_list = []
        # for share in share_tasks:
        #     task_list.append(share.task)
        # if task in task_list:
        #     raise forms.ValidationError('ShareTask with this task has already been created.')
        return self.cleaned_data

todo_backend/todo/api/views.py
from rest_framework import viewsets
from ..models import ToDoTask
from .serializers import ToDoTaskSerializer
from rest_framework.permissions import IsAuthenticated


class ToDoViewSet(viewsets.ModelViewSet):
    serializer_class = ToDoTaskSerializer
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        return ToDoTask.objects.filter(task_creator=self.request.user)

    def perform_create(self, serializer):
        serializer.save(task_creator=self.request.user)

todo_backend/todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
import json
from django.views.generic import *
from django.http import HttpResponseRedirect, JsonResponse, Http404
from .forms import UserRegistrationForm, UserAuthenticationForm, CreateTaskForm, UpdateTaskForm, SearchForm, CommentForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from .models import *
import logging
log = logging.getLogger(__name__)

User = get_user_model()


class UserRegistrationView(CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'registration.html'
    main_page = 'to_do:main'
    context_object_name = 'form'

    def get(self, request):
        context = {}
        if request.user.is_authenticated():
            return redirect(self.main_page)
        context['form'] = self.form_class
        return render(request, self.template_name, context=context)

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data['email']
        password = form.cleaned_data['password1']
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect(self.main_page)


class UserLoginView(FormView):
    form_class = UserAuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy('to_do:main')
    home_page = reverse_lazy('to_do:main')
    logout_url = reverse_lazy('to_do:logout')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(self.home_page)
        return super(UserLoginView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            if next_url == self.logout_url:
                return self.home_page
            return next_url
        else:
            return self.home_page

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        login(self.request, user)
        if user.is_active:
            login(self.request, user)
            return redirect(self.success_url)
        else:
            return self.form_invalid(form)


class UserLogoutView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('to_do:login')
    login_url = reverse_lazy('to_do:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(UserLogoutView, self).get(request, *args, **kwargs)


class MainPageView(TemplateView):
    template_name = 'main.html'


class CreateToDoView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'todo_create.html'
    form_class = CreateTaskForm
    login_url = reverse_lazy('to_do:login')
    success_url = reverse_lazy('to_do:create')
    success_message = 'Task created successfully'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def get_success_message(self, cleaned_data):
        return self.success_message

    def form_valid(self, form):
        task = form.save(commit=False)
        task.task_creator = self.request.user
        task.save()
        return super(CreateToDoView, self).form_valid(form)


class ToDoListView(LoginRequiredMixin, ListView):
    model = ToDoTask
    template_name = 'todo_list.html'
    login_page = 'to_do:login'
    login_url = reverse_lazy('to_do:login')

    def get_queryset(self):
        return self.model.objects.filter(task_creator=self.request.user)

    def get(self, request):
        return render(request, self.template_name, {'todo_list': self.get_queryset()})


class UpdateToDoView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = ToDoTask
    template_name = 'todo_update.html'
    form_class = UpdateTaskForm
    login_url = reverse_lazy('to_do:login')
    success_message = 'Task updated successfully'

    def get_object(self, queryset=None):
        return get_object_or_404(ToDoTask, pk=self.kwargs['pk'])

    def get_success_url(self):
        return reverse('to_do:update', args=(self.get_object().pk,))

    def get(self, request, pk):
        context = {}
        context['todo'] = self.get_object()
        context['form'] = self.form_class
        if not request.user.is_authenticated():
            return redirect(self.login_page)
        return render(request, self.template_name, context=context)

    def get_success_message(self, cleaned_data):
        return self.success_message

    def form_valid(self, form):
        task = form.save(commit=False)
        task.task_creator = self.request.user
        task.save()
        return super(UpdateToDoView, self).form_valid(form)


class DeleteToDoView(LoginRequiredMixin, DeleteView):
    model = ToDoTask
    template_name = 'todo_delete.html'
    login_url = reverse_lazy('to_do:login')
    success_url = reverse_lazy('to_do:deleted')
    success_message = 'Task deleted successfully'

    def get_object(self, queryset=None):
        return get_object_or_404(ToDoTask, pk=self.kwargs['pk'])

    def get(self, request, pk):
        context = {}
        context['todo'] = self.get_object()
        return render(request, self.template_name, context=context)


class DeletedView(TemplateView):
    template_name = 'deleted.html'


class ShareTaskView(LoginRequiredMixin, View):
    template_name = 'share_task.html'
    form_class = SearchForm
    login_url = reverse_lazy('to_do:login')

    def get_todo(self, pk):
        return get_object_or_404(ToDoTask, pk=pk)

    def get(self, request, pk):
        context = {}
        context['form'] = self.form_class
        context['todo'] = self.get_todo(pk)
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request, pk):
        context = {}
        return_dict = dict()
        data = request.POST
        method = data.get('method')
        if method:
            if method == 'share':
                user_id = data.get('user_id')
                status = data.get('status')
                log.debug(type(status))
                log.debug(data)
                log.debug(type(data))
                user = get_object_or_404(User, pk=user_id)
                task = self.get_todo(pk)
                share = ShareTask.objects.filter(task=task, user=user).last()
                is_attend = 0
                read_comment = False
                if status == 'true':
                    read_comment = True
                if share:
                    share.delete()
                    is_attend = 0
                else:
                    ShareTask.objects.create(task=task, user=user, read_and_comment=read_comment)
                    is_attend = 1
                return_dict['comment'] = read_comment
                return_dict['status'] = status
                return_dict['is_attend'] = is_attend
                return JsonResponse(return_dict, status=200)
        else:
            form = self.form_class(request.POST)
            if form.is_valid():
                user_name = form.cleaned_data['user_name']
                users = User.objects.filter(Q(first_name__icontains=user_name) |
                                Q(email__icontains=user_name), is_superuser=False).exclude(pk=self.request.user.pk)
                context['users'] = users
            else:
                context['errors'] = form.errors
        context['form'] = self.form_class(request.POST)
        context['result'] = self.request.POST.get('user_name')
        context['todo'] = self.get_todo(pk)
        return render(request, self.template_name, context)


class TaskDetailView(LoginRequiredMixin, View):
    model = ToDoTask
    template_name = 'todo_detail.html'
    form_class = CommentForm
    login_url = reverse_lazy('to_do:login')
    home_page = 'to_do:main'

    def get_task(self, pk):
        task = get_object_or_404(self.model, pk=pk)
        if task.task_creator != self.request.user:
            share_task = self.request.user.sharetask_set.filter(task__pk=pk).last()
            if share_task:
                return share_task.task
            else:
                raise Http404
        else:
            return task

    def get_comments(self, pk):
        task = self.get_task(pk)
        comments = TaskComment.objects.filter(task=task).order_by('created_at')
        return comments

    def let_comments(self, pk):
        is_show_comments = True
        task = get_object_or_404(self.model, pk=pk)
        if task.task_creator != self.request.user:
            share_task = self.request.user.sharetask_set.filter(task__pk=pk).last()
            if share_task:
                if not share_task.read_and_comment:
                    is_show_comments = False
        return is_show_comments

    def get(self, request, pk):
        context = {}
        context['is_show'] = self.let_comments(pk)
        context['task'] = self.get_task(pk)
        context['form'] = self.form_class()
        context['comments'] = self.get_comments(pk)
        return render(request, self.template_name, context)

    def post(self, request, pk):
        form = self.form_class(request.POST)
        task = self.get_task(pk)
        context = {}
        if form.is_valid():
            comment = form.cleaned_data['comment']
            comment_user = request.user
            TaskComment.objects.create(comment_text=comment, task=task, comment_user=comment_user)
        else:
            context['errors'] = form.errors
        context['form'] = self.form_class(request.POST)
        context['task'] = task

todo_backend/todo/templates/deleted.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>Deleted info</title>
{% endblock %}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2"><h2>Deleted info</h2></strong>
            {% include 'menu_list.html' %}
            <div class="success d-flex">
                                <img src="{% static 'todo/images/success-img.png' %}" alt="success">
                                <h3>Task deleted successfully!</h3>
            </div>
        </div>
{% endblock %}

todo_backend/todo/templates/login.html
{% extends 'base.html' %}
{% block title %}
    <title>Sign In</title>
{% endblock %}
{% load widget_tweaks %}}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2">Sign In</strong>
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.non_field_errors %} <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div> {% endif %}
                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                    {% if field.errors %} <div class="alert alert-danger" role="alert">{{ field.errors.as_text }}</div> {% endif %}
                                    <div class="f col-xs-8">
                                        {{ field|add_class:'form-control news-input font-nimbus-m log-field' }}
                                    </div>
                                    {{ field.placeholder }}
                                </div>
                            {% endfor %}
                    <div class="form-group">
                        <div class="col-xs-offset-4 col-xs-8">
                            <input class="btn btn-primary" type="submit" value="Войти" />
                        </div>
                    </div>
        </form>
         <div class="text-f col-xs-8">
                                    <a  href="{% url 'to_do:registration' %}">Sign Up</a><br/>
                                    <!--<a  href="">Забыли пароль?</a>-->
                                </div>
        </div>
{% endblock %}

todo_backend/todo/templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>{{ message }}</p>
</body>
</html>

todo_backend/todo/templates/main.html
{% extends 'base.html' %}
{% block title %}
    <title>Main page</title>
{% endblock %}
{% block content %}

        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2">To Do App Main page</strong>
            {% if request.user.is_authenticated %}
                <a href="{% url 'to_do:logout' %}" class="btn btn-info" role="button"  style="margin-top:10px;">Sign out</a>
                <a href="{% url 'to_do:create' %}" class="btn btn-info" role="button"  style="margin-top:10px;">Create To do</a>
                <a href="{% url 'to_do:list' %}" class="btn btn-info" role="button" style="margin-top:10px;">Tasks list</a>
                <a href="{% url 'to_do:shared_tasks' %}" class="btn btn-info" role="button" style="margin-top:10px;">Shared Tasks</a>
            {% else %}
                <a href="{% url 'to_do:login' %}" class="btn btn-info" role="button" style="margin-top:10px;">Sign in</a>
            {% endif %}
                <a href="{% url 'to_do:registration' %}" class="btn btn-info" role="button" style="margin-top:10px;">Sign up</a>
        </div>

{% endblock %}

todo_backend/todo/templates/menu_list.html
<ul class="list-inline">
{% if 'list' in request.path %}
    <li class="list-inline-item"><a href="{% url 'to_do:main' %}">Main Page</a><br/></li>
    <li class="list-inline-item"><a href="{% url 'to_do:create' %}">Create To do</a><br/></li>
{% elif 'update' in request.path or 'delete' in request.path or 'deleted' in request.path %}
    <li class="list-inline-item"><a href="{% url 'to_do:main' %}">Main Page</a><br/></li>
    <li class="list-inline-item"><a href="{% url 'to_do:create' %}">Create To do</a><br/></li>
    <li class="list-inline-item"><a href="{% url 'to_do:list' %}">To do List</a><br/></li>
{% else %}
    <li class="list-inline-item"><a href="{% url 'to_do:main' %}">Main Page</a><br/></li>
    <li class="list-inline-item"><a href="{% url 'to_do:list' %}">To do list</a><br/></li>
{% endif %}
    <li class="list-inline-item"><a href="{% url 'to_do:shared_tasks' %}">Shared Tasks</a><br/></li>
     <li class="list-inline-item"><a href="{% url 'to_do:logout' %}">Sign Out</a></li>
</ul>

todo_backend/todo/templates/registration.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
    <title>Registration</title>
{% endblock %}
{% block content %}

        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2">Registration</strong>
            <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.non_fields_errors %}<div class="alert alert-danger" role="danger">{{ form.non_fields_errors }}</div>{% endif %}
            {% for field in form.visible_fields %}
                {% if field.html_name == 'accept' %}
                    <div class="form-group">
                        {% if field.errors %}<div class="alert alert-danger" role="danger">{{ form.errors.as_text }}</div>{% endif %}
                        <label class="col-xs-4 control-label">{{ field.label }}</label>
                        <div class="f col-xs-8">
                            {{ field|add_class:'checkbox font-nimbus-m'}}
                        </div>
                    </div>
                {% else %}
                     <div class="form-group">
                        {% if field.errors %}<div class="alert alert-danger" role="danger">{{ form.errors.as_text }}</div>{% endif %}
                         <div class="f col-xs-8">
                             {{ field|add_class:'form-control font-nimbus-m' }}
                         </div>
                        {{ field.placeholder }}
                    </div>
                {% endif %}
            {% endfor %}
             <div class="form-group">
                            <div class="col-xs-offset-4 col-xs-8">
                                <input class="btn btn-primary" type="submit" value="Зарегестрироваться" />
                            </div>
                 <a href="{% url 'to_do:login' %}" class="btn btn-info" role="button" style="margin-top:10px;">Войти</a>
             </div>
        </form>

        </div>

{% endblock %}

todo_backend/todo/templates/share_task.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load todo_tags %}
{% block title %}
    <title>Search User</title>
{% endblock %}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2"><h2>Share Task</h2></strong>
            {% include 'menu_list.html' %}
            <form method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                 <div class="form-group">
                                <div class="input-group date" style="width:500px;">
                                    <label class="to_do_label" for="user_name">Search</label>
                                    {% if errors %}
                                        <input placeholder="User name or email" type='text' name="user_name" class="form-control" id='user_name' style="width:200px; border: 2px solid #ff0000;" />
                                    {% else %}
                                        <input placeholder="User name or email" type='text' name="user_name" class="form-control" id='user_name' style="width:200px;" />
                                    {% endif %}
                                </div>
                 </div>
                <div class="form-group">
                        <div class="col-xs-offset-4 col-xs-8">
                            <input class="btn btn-primary" type="submit" value="Search" />
                        </div>
                    </div>
            </form>
            {% if request.method == 'POST' and result %}
            {% if users %}
                <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">User name</th>
      <th scope="col">Share</th>
      <th scope="col">Read or Read & Comment</th>
    </tr>
  </thead>
  <tbody>
    {% for user in users %}
    <tr class="share_block">
      <td>{% if user.first_name %}{{ user.first_name }} {{ user.last_name }}{% else %}{{ user.email }}{% endif %}</td>

        <td>
            <a href="" class="share" data-user_id="{{ user.id }}">
           {% if user.pk|get_user_attend:todo.pk %}
            Remove form Share list
           {% else %}
             Add to Share list
           {% endif %}
        </a>

        </td>
        <td>
            <input type="checkbox" name="share_box">
        </td>

    </tr>
  {% endfor %}
  </tbody>
</table>
            {% else %}
                <h3 style="color:red;">Users not found</h3>
            {% endif %}
            {% endif %}
        </div>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'todo/js/main.js' %}"></script>
{% endblock %}

todo_backend/todo/templates/shared_tasks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>Shared Tasks</title>
{% endblock %}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2"><h2>Shared Tasks</h2></strong>
            {% include 'menu_list.html' %}
        {% if tasks %}
            <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Task title</th>
        <th scope="col">Comment</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr>
      <td>{{ task.title }}</td>
        <td>
          <a href="{% url 'to_do:task' task.pk %}">
          <i class="fas fa-share"></i>
        </a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% else %}
            <h3>Empty Shared tasks list</h3>
            {% endif %}
        </div>
{% endblock %}

todo_backend/todo/templates/todo_delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>To do Delete</title>
{% endblock %}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2"><h2>Update To do</h2></strong>
            {% include 'menu_list.html' %}
            <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class='col-sm-6'>
                            <strong><p>Do yo want to delete <i style="color:red;">{{ todo.title }}</i>???</p></strong>
                        </div>
                    </div>
                </div>
                    <div class="form-group">
                        <div class="col-xs-offset-4 col-xs-8">
                            <input class="btn btn-danger" type="submit" value="Delete" />
                            <a href="{% url 'to_do:list' %}" class="btn btn-info" role="button">Cancel</a>
                        </div>
                    </div>
        </form>
        </div>
{% endblock %}

todo_backend/todo/templates/todo_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    <title>To do list</title>
{% endblock %}
{% block content %}
        <div class="col-sm-12 col-md-6">
            <strong class="text-muted d-block mb-2"><h2>Create To do</h2></strong>
            {% include 'menu_list.html' %}
        {% if todo_list %}
            <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Task title</th>
      <th scope="col">Description</th>
      <th scope="col">End date</th>
        <th scope="col">Edit</th>
       <th scope="col">Share</th>
         <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in todo_list %}
    <tr>
      <td><a href="{% url 'to_do:task' todo.pk %}">{{ todo.title }}</a></td>
      <td>{{ todo.description|truncatechars:50 }}...</td>
      <td>{{ todo.end_date|date:'d-m-Y H:i' }}</td>
      <td>
          <a href="{% url 'to_do:update' todo.pk %}">
          <i class="fas fa-edit"></i>
        </a>
      </td>
        <td>
          <a href="{% url 'to_do:share' todo.pk %}">
          <i class="fas fa-share"></i>
        </a>
      </td>
          <td>
          <a href="{% url 'to_do:delete' todo.pk %}">
          <i class="fas fa-trash"></i>
        </a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
    {% else %}
            <h3>Empty To do list</h3>
            {% endif %}
        </div>
{% endblock %}